- name: ensure lookup in /etc/hosts before dns
  lineinfile: line="order hosts,bind"
              regexp="^\s*order\s.*"
              dest="/etc/host.conf"
              insertbefore="^\s*multi\s.*"

- name: add entries of other NATed hosts to /etc/hosts
  lineinfile: line="{{ item.value }}    {{ item.key }}"
              dest="/etc/hosts"
  with_dict: other_nat_hosts
