- name: check if node exists
  stat: path={{ tahoe_basedir }}/node
  register: check_node_dir

- name: create new node
  command: "tahoe create-client -C {{ tahoe_basedir }}/node"
  when: check_node_dir.stat.exists == false

- name: provide default configuration
  copy: src=tahoe-default.cfg
        dest="{{ tahoe_basedir }}/node/tahoe.cfg"
        force=no

- name: set introducer furl
  ini_file: dest="{{ tahoe_basedir }}/node/tahoe.cfg"
            section=client
            option=introducer.furl
            value='{{ introducer_furl }}'
