- name: install rsyslog
  apt: package=rsyslog

- name: install logrotate
  apt: package=logrotate

- name: install logcheck
  apt: package=logcheck

- name: add entries of other NATed hosts to /etc/hosts
  lineinfile: line="FQDN=0"
              regexp="^\s*FQDN\s*=.*"
              dest="/etc/logcheck/logcheck.conf"

- shell: dpkg-query -W 'postfix'
  ignore_errors: True
  register: postfix_is_installed

- file: src=/opt/admintools/etc/logcheck/ignore.d.server/postfix-extra
        dest=/etc/logcheck/ignore.d.server/postfix-extra
        state=link
